services:
  - type: web
    name: blast-crackers-api
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install
    startCommand: npm run migrate && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.qdzmkxrtquovradsjkuh:Anishbosco%402004@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: blast_crackers_super_secret_jwt_key_2026_production
      - key: FRONTEND_URL
        value: https://client-zeta-six-38.vercel.app
      - key: CORS_ORIGIN
        value: https://client-zeta-six-38.vercel.app
      - key: SHOP_UPI_ID
        value: YOUR_UPI_ID@upi
      - key: SHOP_NAME
        value: Blast Crackers Sivakasi
      - key: REQUIRE_UTR
        value: "true"
      - key: PAYMENT_EXPIRY_MINUTES
        value: "15"
